blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/thezykedev/protocolo-sismo-ve/discussions
    about: Usa Discussions para ideas abiertas o preguntas generales.
